spring:
  application:
    name: INCLOVE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

resend:
  api-key: ${RESEND_API_KEY}
  from: ${FROM}

google:
  client-id: ${GOOGLE_CLIENT_ID}
